message error:
  $ dune exec ola error.lua
  lexing parsing ...
  File "error.lua", line 3, char 9: Syntax error
  $ dune exec ola error_require.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  lexing parsing ...
  Interpretation error: error loading module error_require_ko.lua: Syntax error
