goto operations:
  $ dune exec ola goto.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  1
  2
  5
  4
  7
  Interpretation error: no visible label for <goto> l42
