metatables operations:
  $ dune exec ola metatable.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  nil
  nil
  nil
  nil
  protected metatable!
  nil
  value_mt2
