stdlib require function:
  $ dune exec ola stdlib_require.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  I'm in mod!
  string
  hello, world global!
  string
  hello, world local!
  number
  42
