binop typer checks:
  $ dune exec ola bitwise_binop_float.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  File "bitwise_binop_float.lua", line 5, char 6: Evaluation error: number has no integer representation: 1.5
