recursive function typer checks:
  $ dune exec ola function_rec.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Typing error: attempt to call a nil value
