functioncall typer checks:
  $ dune exec ola functioncall_1.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Typing error: attempt to call a nil value
  $ dune exec ola functioncall_2.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Typing error: attempt to call a non function value
