metatable typer checks:
  $ dune exec ola metatable_1.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Interpretation error: Typing error: bad argument #1 to 'setmetatable' (nil or table expected)
  $ dune exec ola metatable_2.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Interpretation error: Typing error: bad argument #1 to 'setmetatable' (nil or table expected)
  $ dune exec ola metatable_3.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Interpretation error: Typing error: bad argument #2 to 'setmetatable' (nil or table expected)
  $ dune exec ola metatable_4.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Interpretation error: Typing error: bad argument #2 to 'setmetatable' (nil or table expected)
  $ dune exec ola metatable_5.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  protected metatable!
  Interpretation error: Typing error: cannot change a protected metatable
