table typer checks:
  $ dune exec ola table.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  42
  File "table.lua", line 3, char 5: Typing error: attempt to index a non table value
