table typer checks:
  $ dune exec ola table.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  42
  Interpretation error: Typing error: attempt to index a non table value
