typer checks:
  $ dune exec ola typer.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  false
  false
  true
  20
  10
  10
  20
  1str
  1.1str
  1
  nil
  
  while_void
  while_t
  while_42
  repeat
  42
  File "typer.lua", line 112, char 12: Typing error: attempt to perform arithmetic on a boolean value
  $ dune exec ola num_of_str.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  File "num_of_str.lua", line 1, char 11: Evaluation error: attempt to perform on a string (str) value
