  $ dune exec ola even_odd.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  true, false
  true, false
  true, false
  true, false
  true, false
  true, false
