  $ dune exec ola oop_advanced_2.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Balance checking_account: 90
  nil
  Error block_account: impossible withdrawal!
  Balance block_account: 6000 - limit: 10000
  nil
