  $ dune exec ola oop_advanced_1.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Balance checking_account: 90
  Impossible withdrawal!
  Balance block_account: 6000 - limit: 10000
