first class functions:
  $ dune exec ola callReturnedFunction.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  My values are
  a
  true
  1
  -100
