simple return function example:
  $ dune exec ola simpleReturn.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  Too low! Guess higher
  Too low! Guess higher
  Too high! Guess lower
  You guessed it!
