swap function:
  $ dune exec ola swapFuncs.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  I am f
  I am g
  Now, time for a switcharoo
  I am g
  I am f
