  $ dune exec ola array.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  size, 10
  attempt to perform an incorrect key for an array, 5
  attempt to perform an incorrect key for an array, ko
  attempt to perform an incorrect key for an array, true
  attempt to perform an incorrect key for an array, 1.1
  {21, nil, 42, nil, nil, nil, nil, nil, hello, world!, false, }
  21
  21
