  $ dune exec ola linked_list.lua
  lexing parsing ...
  static analyses ...
  stdlib loading ...
  scope analysis ...
  interprete ...
  linked_list size, 3
  84
  42
  21
  stack size, 3
  stack top, 84
  stack size, 2
  stack top, 42
  42
  21
